### PR TITLE
Full Calendar 3.9.0 fixing refs

### PR DESCRIPTION
**Pull request by mariohmol**
Hi.. another PR might be useful..

to make it easier to other colaborate.. if u can create an org with this repo and put some contributors there to help manage the repo

bests

### CODE REVIEW

**Comment by Jamaks** [comment]
@mariohmol 
I transfer this repo to new organization, and invite you.

**Comment by mariohmol** [comment]
Thanks!! @Jamaks can u double check pretty quick if this still working a expected?

**Comment by Jamaks** [comment]
@mariohmol 
See https://github.com/ng-fullcalendar/ng-fullcalendar-demo/tree/pull_144 

ERROR in node_modules/ng-fullcalendar/node_modules/fullcalendar/dist/fullcalendar.d.ts(695,36): error TS2304: Cannot find name 'JQueryPromise'


Jquery typing proplems

**Comment by mariohmol** [comment]
@Jamaks I'm runnning this project here with branch 144 and its working good.. i dont see this error.. is not missing a install or anything like that?

**Comment by mariohmol** [comment]
@antoinepairet did u test this version? does it works for u?

**Comment by maciejrybczonek** [comment]
👍

**Comment by vladimirsvicevicsrb** [comment]
When it is planned for new version that support 3.9.0 to be published? Thanks 👍

**Comment by mariohmol** [comment]
@Jamaks saw some errors but i cant reproduce it here..  can u double check please?

**Comment by irustm** [comment]
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins

**Pull request closed without merging**
